version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build: server/API/
    ports:
      - 5000:80
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80