version: '3.4'

services:
  api:
    image: myproject.api
    build:
      context: .
      dockerfile: backend/MyProject/API/Dockerfile
    ports:
      - 5000:80
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80