name: Build & Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./server
    - name: Build
      run: dotnet build ./server --no-restore
    - name: Test
      run: dotnet test ./server --no-build --verbosity normal
    - name: Structure OS
      run: echo $(ls)
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      # Переменные окружения
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      USER_NAME: ${{ secrets.USER_NAME }}
    steps:
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./my-deploy
          host: ${{ secrets.SERVER_IP }}
          remote: ${{ secrets.SERVER_DIR }}
          port: ${{ secrets.SERVER_PORT }}
          user: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
